# Generated by Django 2.2.5 on 2019-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_cv', models.FileField(upload_to='cv_teacher/')),
            ],
        ),
    ]
