# Generated by Django 2.2.5 on 2019-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_studenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='second_process',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='test_analyse',
            field=models.TextField(null=True),
        ),
    ]
