# Generated by Django 2.2.5 on 2019-09-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Quest_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_h', models.CharField(max_length=30)),
                ('sujet_h', models.CharField(max_length=100)),
                ('message_h', models.TextField(max_length=500)),
                ('email_h', models.CharField(max_length=30)),
                ('phone_h', models.IntegerField()),
                ('created_at_h', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Quest_ans')),
            ],
        ),
    ]
