# Generated by Django 2.2.5 on 2019-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.IntegerField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
