# Generated by Django 2.2.5 on 2019-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190913_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_h', models.CharField(max_length=30)),
                ('sujet_h', models.CharField(max_length=100)),
                ('message_h', models.TextField(max_length=500)),
                ('email_h', models.CharField(max_length=30)),
                ('phone_h', models.IntegerField()),
                ('created_at_h', models.DateTimeField(auto_now_add=True)),
                ('answer_h_0', models.TextField(blank=True, max_length=500)),
                ('answer_h_1', models.TextField(blank=True, max_length=500)),
                ('answer_h_2', models.TextField(blank=True, max_length=500)),
                ('answer_h_3', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
